const passport = require('passport');
// Google authentication strategy for PassportJS
const GoogleStrategy = require('passport-google-oauth20').Strategy;
// register Google+ API https://console.developers.google.com
// Google API credentials
const mongoose = require('mongoose');
const keys = require('../config/keys');

// retrieve the users collection from MongoDB, created in index.js during initialization
const User = mongoose.model('users');

// serialize the user to generate a unique token
// the first argument 'user' is the MongoDB record returned from done() function in passport.use
passport.serializeUser((user, done) => {
	// use the instance id property generated by MongoDB record as a unique identifier
	// the reason we use MongoDB record id is that we can then use multiple authentication providers
	done(null, user.id);
});

// deserialize the model instance and attach it to req.user
passport.deserializeUser((id, done) => {
	// find the MongoDB record from 'users' collection with the matched id
	User.findById(id)
		.then((user) => {
			done(null, user);
		})
});


// inform Express to handle OAuth using PassportJS
passport.use(
	// Google authentication
	new GoogleStrategy(
		{
			clientID: keys.googleClientID,
			clientSecret: keys.googleClientSecret,
			callbackURL: '/auth/google/callback',
			proxy: true
		}, 
		// this callback function is called when a Google user profile is returned
		// we will either create a new user or retrieve the user from database based on its existence
		async (accessToken, refreshToken, profile, done) => {
			// check if the user is already in database
			const existingUser = await User.findOne({ googleId: profile.id });

			if (existingUser) {
				// return the existing user, which will be processed in passport.serializeUser()
				// the done method should be called to indicate authentication is completed
				// the first argument is an error object, the second argument is the user record
				done(null, existingUser);
			} else {
				// create a new record in MongoDB users collection
				const user = await new User({ googleId: profile.id }).save();
				done(null, user);
			}
		}
	)
);